version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bdtask
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    depends_on:
      - postgres
    ports:
      - "8086:8086"
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
volumes:
  postgres-data: